name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmetsaz/github-actions-demo/docker-build-template@master
        with:
          image_name: github-actions
          tag: $GITHUB_RUN_NUMBER
          registry_username: ${{secrets.DOCKER_USERNAME}}
          registry_password: ${{secrets.DOCKER_PASSWORD}}
  
  kubernetes-deployment:
    runs-on: ubuntu-latest
    environment: test
    needs: docker-build
    steps:
      - uses: ahmetsaz/github-actions-demo/kubernetes-deployment@master
        with:
          image_name: github-actions
          tag: $GITHUB_RUN_NUMBER
          registry_username: ${{secrets.DOCKER_USERNAME}}
          registry_password: ${{secrets.DOCKER_PASSWORD}}
    
  # docker-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
        
  #     - name: Docker Login
  #       uses: docker/login-action@v2.0.0
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Docker Build & Push
  #       run: |
  #         cd app
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/github-actions:${{ github.sha }} .
  #         docker push ${{ secrets.DOCKER_USERNAME }}/github-actions:${{ github.sha }}
  
  # deploy-to-test:
  #   runs-on: ubuntu-latest
  #   environment: test
  #   needs: docker-build
  #   steps:
  #   - name: Set Context
  #     uses: azure/k8s-set-context@v2
  #     with:
  #        method: kubeconfig
  #        kubeconfig: ${{ secrets.KUBECONFIG }}
         
  #   - name: Set Image
  #     run: |
  #       kubectl --namespace=default set image deployment/demo-app github-actions=${{ secrets.DOCKER_USERNAME }}/github-actions:${{ github.sha }} 
   

      
