name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build & Push
        run: |
          cd app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/github-actions:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/github-actions:${{ github.sha }}
